language: node_js
node_js: stable

# branches:
#   only:
#     - develop

env:
  global:
    - GH_REF: github.com/equipindustry/slides-aws-overview.git
    - GH_BRANCH: gh-pages
    - USER_NAME: '@slovacus'
    - USER_EMAIL: 'slovacus@gmail.com'

cache:
  directories:
    - $HOME/.yarn

before_install:
  - node --version
  - yarn --version

install:
  - yarn install

script:
  - yarn build

after_script:
  - cd ./public
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git branch --force gh-pages
  - git checkout gh-pages
  - git add .
  - git commit -m "Implement build for branch gh-pages"
  # - git push --force https://$GH_TOKEN@$GH_REF develop:$GH_BRANCH
  - git push --force --quiet "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" gh-pages:gh-pages
